server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  # 1) Docker container logs (app1, app2, nginx, etc.)
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
        regex: '/(.*)'
      - source_labels: ['__meta_docker_container_name']
        target_label: 'job'
        regex: '/(.*)'

    pipeline_stages:
      - docker: {}   # decode docker log json (if present)
      - json:
          expressions:
            level: level
            message: message
            app: app
            reqId: reqId
            route: route
            status: status
            durationMs: durationMs
      - labels:
          app:
          level:
          container:
      - timestamp:
          source: time
          format: RFC3339Nano
          action_on_failure: skip

  # 2) NGINX access logs (JSON)
  - job_name: nginx-access
    static_configs:
      - targets: [ "nginx" ]
        labels:
          job: nginx-access
          app: nginx
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - json:
          expressions:
            time: time
            remote_ip: remote_ip
            method: method
            url: url
            status: status
            bytes: bytes
            request_time: request_time
            upstream_time: upstream_time
            user_agent: user_agent
      - labels:
          app:
          method:
          status:
      - timestamp:
          source: time
          format: RFC3339
          action_on_failure: skip

  # 3) NGINX error logs (plain text, not JSON)
  - job_name: nginx-error
    static_configs:
      - targets: [ "nginx" ]
        labels:
          job: nginx-error
          app: nginx
          __path__: /var/log/nginx/error.log
